### ISSUE TITLE
Does not generate any output

### ISSUE THREAD

**Issue by UberStorm** [ToonCrafter/ToonCrafter#14]
after running ToonCrafter, it just generates forever and nothing happens for almost 40 minutes.
My GPU is RTX 4070Ti.

```
AE working on z of shape (1, 4, 32, 32) = 4096 dimensions.
checkpoints/tooncrafter_512_interp_v1/model.ckpt
>>> model checkpoint loaded.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Global seed set to 789
start: an anime scene 2024-06-01 11:15:03
C:\ToonCrafter-for-windows\venv\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
```

**Comment by UberStorm** [comment]
closed because it works, especially when using this comfyui custom node
https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/

**Comment by WestbrookZero** [comment]
> after running ToonCrafter, it just generates forever and nothing happens for almost 40 minutes. My GPU is RTX 4070Ti.
> 
> ```
> AE working on z of shape (1, 4, 32, 32) = 4096 dimensions.
> checkpoints/tooncrafter_512_interp_v1/model.ckpt
> >>> model checkpoint loaded.
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> Global seed set to 789
> start: an anime scene 2024-06-01 11:15:03
> C:\ToonCrafter-for-windows\venv\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
>   warnings.warn(
> ```

I had the same problem. How did you solve it in this project @UberStorm
