### ISSUE TITLE
ModuleNotFoundError: No module named 'decord'

### ISSUE THREAD

**Issue by FemBoxbrawl** [ToonCrafter/ToonCrafter#4]
I have no idea how to solve this. this happened after trying to run python gradio_app.py

H:\AI\ToonCrafter>  python gradio_app.py
Traceback (most recent call last):
  File "H:\AI\ToonCrafter\gradio_app.py", line 4, in <module>
    from scripts.gradio.i2v_test_application import Image2Video
  File "H:\AI\ToonCrafter\scripts\gradio\i2v_test_application.py", line 5, in <module>
    from scripts.evaluation.funcs import load_model_checkpoint, save_videos, batch_ddim_sampling, get_latent_z
  File "H:\AI\ToonCrafter\scripts\evaluation\funcs.py", line 4, in <module>
    from decord import VideoReader, cpu
ModuleNotFoundError: No module named 'decord'

H:\AI\ToonCrafter>

**Comment by adbrasi** [comment]
pip install decord==0.6.0

**Comment by youkotwo** [comment]
for every error like this:
ModuleNotFoundError: No module named 'exemple'
you just have to open requierements.txt , find the coresponding line and enter in cmd:
pip install exemple
and the issue should be fixed

**Comment by FemBoxbrawl** [comment]
thanks for the comments, but i switched to comfyui for tooncrafter, thanks anyways
