### ISSUE TITLE
About ComfyUI implement

### ISSUE THREAD

**Issue by Yorha4D** [ToonCrafter/ToonCrafter#6]
@Doubiiu Hello ToonCrafter Team,

We are a team called AIGODLIKE, a group is dedicated to the study of animation and cg technology, and we are excited to share to users that we have discovered your innovative animation technology, ToonCrafter. 

We are currently working on implementing ToonCrafter into ComfyUI, a node-based powerful and modular stable diffusion GUI.

We believe that integrating ToonCrafter into ComfyUI will greatly enhance animation capabilities and provide significant benefits to animation industry. 

Please feel free to reach out if you have any questions or if there are any specific guidelines or licences we should follow during the integration process. We look forward to your feedback and are excited about the possibilities of this collaboration will bring.

Thank you for your time and consideration.

**Comment by nathanshipley** [comment]
FWIW, a version is already implemented in Kijai's Dynamicrafter nodes:

https://github.com/kijai/ComfyUI-DynamiCrafterWrapper

**Comment by Yorha4D** [comment]
https://github.com/AIGODLIKE/ComfyUI-ToonCrafter

https://github.com/ToonCrafter/ToonCrafter/assets/116185401/48b46fe0-9400-4d6f-b881-797df8879ada
